### ISSUE TITLE
Cannot be loaded on Arduino

### ISSUE THREAD

**Issue by hydrastarmaster** [DavidArmstrong/SiderealObjects#1]
Checking on Mega2560:
The test on double/floating hast to be deleted (as we have seen in the case of SiderealPlanets), as per AVR specs. Thus, Example1 can be deleted too.

The sketch cannot be loaded on a Mega2560. SiderealObjectsTables.h is >3kB ... by far too big. A solution can be to move space-objects data on an SD card. For this purpose, the CSV format can be taken into consideration, instead of having a separate "extras" file with explanations. This will give the opportunity to further expand the catalog.

**Comment by DavidArmstrong** [comment]
While I can go along with removing the true double number support for this Library, that is not the primary problem with using the Mega 2560 board.  I've always been under the impression, mistakenly I see now, that the Arduino IDE would allow code to be able to be compiled for different platforms with little or no changes to the code itself.  However, with the Mega being more like a traditional AVR processor, it just doesn't handle using large arrays of data in Flash.  Everything is transferred to RAM on startup.  While there may be some workarounds for this, they are very board specific fixes, which is exactly what I wanted to avoid by going to the Arduino IDE.  (It's platform independent - it should be, or have been, board independent as well.)  Ugh,
I will do an update here, as I see some other routines that need tweaking as well.  However I'm not finding an easy fix for the Mega in particular.  All the 32-bit boards, like the SAMD and Apollo3, are much easier to work with, as they don't require code changes for handling large static arrays.  They just work.

**Comment by hydrastarmaster** [comment]
It can be easy to work all on the same IDE, but this is low-level programming. Each board has its physical specs. For e.g. Apollo3 has 1MB of RAM, while Mega2560 (the biggest AVR) has only 256K and different characteristics. But it will sound very strange to find in the Arduino repository resources that cannot run on Arduino boards.
Mega2560 EEPROM (<256k) can be loaded with a separate sketch and is not transferred into RAM on startup, you have to r/w it in your pgm. Anyway, that's by far too small for a space-objects db: I might argue that even your large array has too little data for a star-pointer. Everything here has to be kept as simple as possible, and those large static arrays are not basic stuff, nor they are human-readable in the way you coded it.
The best solution here (from the AVR point of view) is to have plain data on an SD card file (I suggest a CSV format). You can add it, it's not forbidden to have external hw. SD card can be formatted FAT32, that's a max file size of 4GB , and a card with up to 32GB. That's enough space indeed.

**Comment by DavidArmstrong** [comment]
Created new branch with proposed changes.  Try that.

**Comment by hydrastarmaster** [comment]
New branch it's OK on Mega2560. Thank you.
